### ISSUE TITLE
Not working in Xcode 6.2

### ISSUE THREAD

**Issue by gmaletic** [onevcat/VVDocumenter-Xcode#100]
I know this is a problem that isn't affecting everyone, but VVDocumenter under Xcode 6.2, Alcatraz 1.1, is flat-out not working for me. I type "///" and nothing happens.

**Comment by idStar** [comment]
I have the same issue. I've tried:

1. Installing standalone into Xcode 6.2 by using the `VVDocumenter-Xcode` project itself without Alcatraz. It will build fine, but upon re-start, not show up. I've gotten it to work previously by clearing my `DerivedData` folder and re-building. That however, is no longer working for me.
2. When installing with Alcatraz, it detects VVDocumenter is already installed, but the VVDocumenter menu item doesn't show up and sure enough, the `///` key sequence doesn't work. I tried to remove it via Alcatraz and then re-install via Alcatraz. Sadly, this still didn't work.

Some additional notes:

* The read-me page indicates that with a manual installation, the plug-in would get installed here: `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins`. However, I found that directory didn't exist by default. Even when creating it manually, the plug-in never installed there. Perhaps with Xcode 6.2, there's a newer location this should go, not reflected by the older README file?
* Often times, within the same version of Xcode, the plugin will just stop working, and the install process will need to be repeated, with mixed success.

**Comment by Mozahler** [comment]
I downloaded the latest version, ran it, restarted Xcode and then nothing... So I went to window/VVDocumenter and reviewed the settings (I had changed /// to @@@ in previous versions)  
I closed the window, typed @@@, and voila! everything worked again...

**Comment by onevcat** [comment]
It turned out to be a plugin loading issue in Xcode 6.2. Since there is no report for the same issue in Xcode 6.3 and 7, I am closing this issue.
