### ISSUE TITLE
Not working in Xcode 6.3

### ISSUE THREAD

**Issue by tdquangad2** [onevcat/VVDocumenter-Xcode#105]
It worked on Xcode 6.2
After I upgrade Xcode to 6.3, I cannot use VVDocumenter-Xcode :(

**Comment by MakeZL** [comment]
Xcode6.3 UUID 9F75337B-21B4-4ADC-B558-F9CADF7073A7

**Comment by tdquangad2** [comment]
It worked perfectly! Thanks MakeZL

**Comment by liuxuan30** [comment]
Someone make a pull request for this or the author can fix it?

**Comment by onevcat** [comment]
Already fixed. Please clone the master and build again for Xcode 6.3.

**Comment by YTpro** [comment]
Thanks MakeZL very much,It worked.
