### ISSUE TITLE
not good working in xcode 6.11

### ISSUE THREAD

**Issue by xuqix** [onevcat/VVDocumenter-Xcode#106]
The problem maybe only in my xcode. I type "///" and get a "\t", no other content. I repeated many times to uninstall - install, the problem still exists.What possible reason is that the problem and How can i solution it?

**Comment by onevcat** [comment]
It should an issue with the parser. May I know the context you are trying to insert the documentation?

**Comment by xuqix** [comment]
I am work on the osx10.10 and xcode6.1.1,and I tried to install a different version of xcode(6.2 or 6.3,i forget), the problem still exists.I guess the problem regardless of the version.I tried code in c++ and oc , all have this prblem.

**Comment by onevcat** [comment]
May I ask if you are using some customized keyboard shortcut for "Delete to Beginning of the Line (⌘⌫)“ and "Paste (⌘V)" ? This plugin relies to these two shortcuts to work properly. If you are using other shortcuts for them, you may need to modify the code to get it works.

**Comment by xuqix** [comment]
Wow!This is the problem.I change keyboard shortcut "Paste (⌘V)" to "Control-V".
After i restored the shortcuts,it good working now.
Thanks! :)
