### ISSUE TITLE
Request :  xcode printed comments

### ISSUE THREAD

**Issue by nissaba** [onevcat/VVDocumenter-Xcode#111]
apple comments starts with /*! this will get the next line to show up in the auto-complete as a description of the method

ex:  
/*!
*Bla bla bla
*/

Bla bla bla would show as the method description in the auto-complete. 

it be great if you update this plugin to work with this. 

thanks

**Comment by onevcat** [comment]
Please find the option in the VVDocument preference panel. You can find it in Window -> VVDocumenter menu.

**Comment by nissaba** [comment]
Cool. Thanks :). 

Envoyé de mon iPhone
