### ISSUE TITLE
no working for xcode 6.3.2

### ISSUE THREAD

**Issue by hhb19900618** [onevcat/VVDocumenter-Xcode#117]
no working for xcode 6.3.2,  but xcode 6.3.1 is ok before，why？

**Comment by onevcat** [comment]
UUID is changed in 6.3.2, so you need to download the latest source and build again.

**Comment by hhb19900618** [comment]
I have downloaded the latest version ,but no working still

**Comment by liuxuan30** [comment]
Double check your UUID matches xcode 6.3.2 ones and build it again - Mine is working great, so should be your code problem.

**Comment by hhb19900618** [comment]
i do not know how to do ?

**Comment by LengBinBin** [comment]
Use `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID` and then add the  UUID to VVDocumenter-Xcode -> VVDocumenter-Xcode-Info.plist -> DVTPlugInCompatibilityUUIDs

**Comment by 0x0007de** [comment]
I have added the UUID ,but no working still

**Comment by verma-manish58** [comment]
I have checked in the VVDocumenter-Xcode-Info.plist , the xcode UUID is residing there but the plugin is not showing up in the xcode. Kindly let us have a solution asap.
