### ISSUE TITLE
Swift: Class Description incorrect

### ISSUE THREAD

**Issue by gutenmorgenuhu** [onevcat/VVDocumenter-Xcode#119]
First of all: Thank you for this great plugin.

I have one thing concerning Swift Code Documentation tho. When entering `///` for a class Description, VVDocumenter pastes the regular
```
/**
* Description
*/
```
snippet.
But Xcode will unfortunately display this wrong, using some sort of bullet-list-style
![Image of Xcode displaying wrong](http://i.imgur.com/NpMY4dt.jpg)

I believe, for class documentation, a multiline `///`comment works as intended:

![Image of Xcode displaying correctly](http://i.imgur.com/ZKA77kQ.jpg)

**Comment by onevcat** [comment]
Yes, I agree with you. I will find a time to fix it.

**Comment by gutenmorgenuhu** [comment]
I appreciate your effort and your short responsetime

**Comment by onevcat** [comment]
Should be fixed in #126

**Comment by gutenmorgenuhu** [comment]
Thank you. Great work 






On Wed, Jun 17, 2015 at 8:28 AM -0700, "Wei Wang" <notifications@github.com> wrote:












Should be fixed in #126
