### ISSUE TITLE
Unexpected code bundle “VVDocumenter-Xcode.xcplugin”

### ISSUE THREAD

**Issue by RobinChao** [onevcat/VVDocumenter-Xcode#120]
The “VVDocumenter-Xcode.xcplugin” code bundle is not provided by Apple. Loading code not provided by Apple can have a negative effect on the safety and stability of Xcode or related tools.

**Comment by Vaselineee** [comment]
thank you.

**Comment by onevcat** [comment]
This is a loading behavior of third party plugin in Xcode from version 6.3. I guess I can do nothing for it. :(

**Comment by debolee** [comment]
I met this problem,too. my Xcode version is 6.3.2.

**Comment by onevcat** [comment]
You have to choose "Load bundle" to use plugins. There is nothing we plugins developers could do with it.

**Comment by debolee** [comment]
thank you!

**Comment by debolee** [comment]
I chose "Not Load bundle" when  relaunch Xcode, then I added UUID of Xcode to DVTPlugInCompatibilityUUIDs.

**Comment by debolee** [comment]
I chose "Not load bundle" when relaunch Xcode, then I added UUID of Xcode version to DVTPlugInCompatibilityUUIDs. But How can I change it to "Load bundle" now?
Thanks!
