### ISSUE TITLE
Swift class func not working

### ISSUE THREAD

**Issue by danielborges93** [onevcat/VVDocumenter-Xcode#131]
When you use VVDocumenter above a class function, in Swift, it not working correctly. See the image below.

![captura de tela 2015-06-30 as 16 46 23](https://cloud.githubusercontent.com/assets/1283243/8440311/be50c72c-1f47-11e5-99ff-f6fe68a90968.png)

**Comment by onevcat** [comment]
Oops...I will fix it later.

**Comment by kostiakoval** [comment]
Same for variables 

![screen shot 2015-07-07 at 20 04 12](https://cloud.githubusercontent.com/assets/1086260/8553370/47d24c1e-24e3-11e5-9d39-754925782c66.png)

**Comment by onevcat** [comment]
It is intended behavior for a property (three slash ///).

**Comment by kostiakoval** [comment]
ohh ok :) Sorry 😊

**Comment by DonnaLea** [comment]
I see you are saying that the Swift class documentation shouldn't be showing the documentation with /// Description
But looking at your reference for Swift documentation http://nshipster.com/swift-documentation/ that is how a class is documented. If you're labeling this as a bug, how should a class documentation comment look like then if it isn't /// Description ?

**Comment by onevcat** [comment]
`class` should be documented as `///`, but `class func` not

**Comment by DonnaLea** [comment]
Ah.... I've spent too much time staring at comments and code and missed that detail :P Thanks for clearing up my misunderstanding. :)

**Comment by onevcat** [comment]
Fixed in #160
