### ISSUE TITLE
Stoped working in Xcode 6.3.2

### ISSUE THREAD

**Issue by buffstop** [onevcat/VVDocumenter-Xcode#136]
"///" shortcut stoped working after updating to Xcode 6.3.2. Also disapeared from *Windows* menu.

Thanks for the also great plugin though.

**Comment by onevcat** [comment]
May be you need clone the repo and rebuild the plugin.

Also remember not to "Skip Load bundle" when you open Xcode for the first time.

**Comment by liuxuan30** [comment]
@onevcat if I mistakenly chose Skip load bundle, how to restore it?

**Comment by onevcat** [comment]
Try this:

```bash
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-{your_xcode_version}
```

**Comment by robert121** [comment]
I clone the repo and rebuild the plugin but don't work either

**Comment by ViccAlexander** [comment]
I deleted, and reinstalled the plugin via Alcatraz' package manager, but to no avail. Upon typing the shortcut, it gets deleted, but it's replaced with a tab rather than the actual documentation template. Hmm...

**Comment by onevcat** [comment]
@ViccAlexander Is all documentation template for method/property empty? If it is only a special case, it might be a bug of code detection instead of not working.

**Comment by ViccAlexander** [comment]
Hmm... what do you recommend? P.S. Thanks for an awesome plugin btw.

**Comment by buffstop** [comment]
I'm also using Alcatraz btw.

**Comment by Apolotary** [comment]
Same issue on Xcode 6.4 with or without Alcatraz installation

**Comment by yaqi0212** [comment]
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.3.2

再重新打开Xcode，会再次弹出上面提示，记住点击“Load”

**Comment by onevcat** [comment]
Closing "update and cannot use" issues since it is redeclared in the ReadMe file.
