### ISSUE TITLE
Not working in Xcode 6.4

### ISSUE THREAD

**Issue by RazvanMaris** [onevcat/VVDocumenter-Xcode#137]
Just upgraded to Xcode 6.4 and the documenter is no longer working

**Comment by mrblackus** [comment]
No problem for me with Xcode 6.4, but I had to reinstall Alcatraz (if you installed through it).

**Comment by RazvanMaris** [comment]
Removed and reinstalled the documenter. All back to normal.

**Comment by liuxuan30** [comment]
remember to sync code, recompile and install every time Xcode has upgrade

**Comment by TheLittleBoy** [comment]
Help！  I selected "Skip Bundle"。Now，How should I do？

**Comment by RazvanMaris** [comment]
Probably this will help: http://stackoverflow.com/a/30370283/3510700

**Comment by onevcat** [comment]
If you skipped the bundle loading, you can reset the prompt by 

```
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-{your_xcode_version}
```

**Comment by TheLittleBoy** [comment]
Thanks a lot.

**Comment by DaRkD0G** [comment]
@RazvanMaris  Thanks

"Removed and reinstalled the documenter. All back to normal." And Restart Xcode
