### ISSUE TITLE
Put the delegate automatically

### ISSUE THREAD

**Issue by grosch** [onevcat/VVDocumenter-Xcode#139]
If I have something like this:

///<space>
extension Something : SomeClassDelegate {

When I hit that space, instead of leaving me a field to fill out on the MARK that's created, can you have it notice that there's a protocol already declared and just use that as the default value?  So I'd want to get

// MARK: - SomeClassDelegate

there automatically.

**Comment by onevcat** [comment]
It is a possible improvement and I will implement it later.

**Comment by onevcat** [comment]
Added in #161
