### ISSUE TITLE
Is it possible to adjust the indentation on a function comment

### ISSUE THREAD

**Issue by DonnaLea** [onevcat/VVDocumenter-Xcode#141]
First off, thanks for the great work on a great plugin! 

The default for a function comment in Swift in Xcode has no indentation: 

![screen shot 2015-07-16 at 1 26 02 pm](https://cloud.githubusercontent.com/assets/341445/8734343/4a7c0e00-2bbe-11e5-89cf-f54652f7d6f3.png)

But I would love to have my comment indented like this by default: 
![screen shot 2015-07-16 at 1 27 21 pm](https://cloud.githubusercontent.com/assets/341445/8734367/6cce996e-2bbe-11e5-9d80-c3ba55d866b8.png)

Is it possible to change this somewhere in some config file? I'm using alcatraz to install VVDocumenter-Xcode. 

Thanks in advance!

**Comment by onevcat** [comment]
Currently there is no such option. Since it is a very rare demand, and will not be added into this plugin.

However, you are free to modify the source to implement it. Maybe you just need to add some space in the `-prefixString` in VVBaseCommenter.m.

**Comment by DonnaLea** [comment]
Thanks for the info and quick response.
