### ISSUE TITLE
根本就用不了是怎么回事啊？

### ISSUE THREAD

**Issue by Jvaeyhcd** [onevcat/VVDocumenter-Xcode#146]
在Xcode6.4中根本就没有办法使用是怎么回事啊？

**Comment by onevcat** [comment]
Please do not open an issue if this plugin not work in your newly updated Xcode. Refer to the readme file to find a solution instead.

**Comment by liuxuan30** [comment]
@Jvaeyhcd be polite and behave yourself, nobody force you to use, and you are not entitled to acuse because you paid nothing.

@Jvaeyhcd 礼貌待人，没人逼你用，你没给钱也没权利指责别人用不了，大家都能用就你不能用，瞎嚷嚷什么，自己不会去查原因？
