### ISSUE TITLE
Typing "///" leaves in the first two "/" characters

### ISSUE THREAD

**Issue by michaeleiselsc** [onevcat/VVDocumenter-Xcode#148]
When I type "///", I get:
```
///**
* Returns a singleton instance of SCDiscoverConfiguration
*
*  @return <#return value description#>
*/
```

It looks like it should be removing those first two "/" characters, but I don't know. Any ideas?

**Comment by onevcat** [comment]
Currently this plugin is using the "Delete to Beginning of the Line" shortcut to remove the `///`, which is ⌘⌫ by default. Maybe you changed this shortcut in your Mac? You can check it in the key binding setting in Xcode.

**Comment by michaeleiselsc** [comment]
Perfect, thanks!
