### ISSUE TITLE
Add support for __nullable and __nonnull?

### ISSUE THREAD

**Issue by lexrus** [onevcat/VVDocumenter-Xcode#154]
``` objective-c
/**
 *  搜索 POI 数据
 *
 *  @param NSString!            keyword    搜索的关键词
 *  @param POISearchCompletion? completion 搜索的回调，有结果时数组不为空
 */
- (void)searchPOI:(NSString * __nonnull)keyword completion:(POISearchCompletion __nullable)completion;
```

**Comment by onevcat** [comment]
Thanks. I will consider.

**Comment by mohamede1945** [comment]
Just an opinion, I think this just a redundant information that shouldn't be part of the documentations. It's part of the API signature and compiler can deduce it and tells the user the data types and optional or not.

**Comment by lexrus** [comment]
@mohamede1945 Yes, make sense.
