### ISSUE TITLE
Swift 2.0 in Xcode 7.0 beta 6 (7A192o) no longer use :param: and :returns:

### ISSUE THREAD

**Issue by owenzhao** [onevcat/VVDocumenter-Xcode#166]
http://ericasadun.com/2015/06/14/swift-header-documentation-in-xcode-7/

:param: should change to "- parameter "
:returns: should changes to "- returns: "
Please also notice the spaces in the ""

:param: 应该改为 "- parameter "
:returns: 应该改为 "- returns: "
请留意其中的空格

**Comment by onevcat** [comment]
See #151
