### ISSUE TITLE
增加注释功能

### ISSUE THREAD

**Issue by bingxue314159** [onevcat/VVDocumenter-Xcode#170]
能不能增加两个功能,万分感谢，特别是第2条，经常用到！
1.整个文件的注释，如
/**
 * @file    MyDocViewController.h
 * @brief    主页面.
 * @author    [zyl910](http://www.cnblogs.com/zyl910/)
 * @version    1.0
 * @date    2013-06-07
 *
 * # update （更新日志）
 * [2013-06-07] <zyl910> v1.0
 * + v1.0版发布.    
 */

2.能不能增加属性的注释，如：
UIButton *btnSend;/**< 发送按钮 */
![11](https://cloud.githubusercontent.com/assets/10768058/9751341/01e67124-56d6-11e5-9add-4118210635d5.jpg)

**Comment by onevcat** [comment]
文件注释是不应当也没有必要的。

属性注释已经有了。

**Comment by bingxue314159** [comment]
不好意思哈，没找到属性注释的快捷键，我批的是在属性的右侧！用///没有反应！能教下快捷方式么？万分感谢！

**Comment by onevcat** [comment]
应该是在属性上方添加
