### ISSUE TITLE
Incorrectly adds return type for swift function comment

### ISSUE THREAD

**Issue by keith** [onevcat/VVDocumenter-Xcode#172]
Using VVDocumentor on a function with this format:

```swift
static func abc(def hig: Bool = false,
    completion: (something: Type) -> Void)
{
```

Incorrectly produces this comment:

```
/**
    <#Description#>

    - parameter def:                 <#def description#>
    - parameter completion:     <#completion description#>

    - returns: <#return value description#>
    */
```

Where it should not have the `returns` line.

**Comment by onevcat** [comment]
@keith Thanks for reporting.
Just tried it but it seems work well for me. Are you using the latest version? Would you please try to build from master branch and try again?

**Comment by keith** [comment]
Looks like it was a fluke. Sorry!
