### ISSUE TITLE
[Enhancement] Auto Documentation Generation

### ISSUE THREAD

**Issue by mohamede1945** [onevcat/VVDocumenter-Xcode#173]
I'm talking about something like this http://jautodoc.sourceforge.net/ but for Objective-c and Swift. So if you have a function like this one.

```Objective-c
- (instancetype)initWithDictionary:(NSDictionary *)dictionary;
```
It becomes
```Objective-c
/**
 *  Initialize new instance with dictionary.
 *
 *  @param dictionary The dictionary parameter.
 *
 *  @return The new created instance.
 */
- (instancetype)initWithDictionary:(NSDictionary *)dictionary;
```

What do you think about this feature? I've already done it for my own use, but for an old version of yours (I'll have to update it for your latest changes) and I'd like to know your thoughts before I do a PR.

**Comment by onevcat** [comment]
Hi, @mohamede1945 
Thanks a lot for being interested in contributing.

In my opinion, the Swift or Objective-C APIs are usually verbose, and it seems sometimes meaningless to just repeat the parameter's name (like `@param dictionary The dictionary parameter.` here, it cannot bring the reader any new information about this API). Something more useful should be encouraged to be written.

However, it still could be a good idea to make it an option or wrap it in a `<# #>` tag (which could let users to decide to just use it by typing an `enter` or write their own documentation). We may also need to decide which kind of APIs should be applied with such auto documentation. It would definitely introduce another level of complexity into the project. It is not quite worthy to do it, I guess.

What do you think about it?

Anyway, thanks a lot for using this plugin and it is so great to see the feed back from you :)

**Comment by mohamede1945** [comment]
Hi @onevcat, I think I don't need to mention how wonderful this plugin is. I really appreciate your efforts of doing it and supporting it. I'm sure it saves million of hours for developers around the world.

I totally agree with you in almost everything single word. I also agree, it makes the code more complex.

**Comment by onevcat** [comment]
Thanks! Great to hear that.
