### ISSUE TITLE
Doesn't generate the params and returns

### ISSUE THREAD

**Issue by houmanka** [onevcat/VVDocumenter-Xcode#175]
Hi,
I have installed the plugin and now in the Swift when I type '///' it just gives me 
```
/**
Description
*/
```

Do I need to do anything else in order to get the full param and returns tags?

Thanks

**Comment by onevcat** [comment]
If you can see 
```
/**
Description
*/
```
It means the plugin works.

You need some context to use this plugin. Please try to input `///` above of some `func` to see how it works.

**Comment by houmanka** [comment]
hmmm, Ok I did it on top of the `func` and you are correct.

Please check this
![screen shot 2015-09-15 at 4 33 28 pm](https://cloud.githubusercontent.com/assets/391493/9869501/c4ed5462-5bc7-11e5-8dd6-41dfdf16bde3.png)

Generated via this:
```
 /**
        MakePayment is network call for process Stripe payment
        :param: PaymentModel Object
    
        :param: STPToken needs to be already generated
        
        :returns: Hydrates `self.data`
    
    */
```

When I use your plugin I get this:

![screen shot 2015-09-15 at 4 39 00 pm](https://cloud.githubusercontent.com/assets/391493/9869580/509e95ca-5bc8-11e5-9ff4-14d5328fb1ed.png)

Which is generated by this:

```
    /**
    MakePayment is network call for process Stripe payment
    
    - parameter paymentModel: Payment Model Object
    - parameter stipeToken:   Need to pass the STPToken
    */
```

Is it meant to be like this? Can your plugin make the first kind of documentation?

Thanks

**Comment by onevcat** [comment]
The master branch is for Swift 2.0. If you need to use it for Swift 1.x, please use Xcode6 branch instead.
