### ISSUE TITLE
Everything is a code block

### ISSUE THREAD

**Issue by rolandleth** [onevcat/VVDocumenter-Xcode#181]
Hey,

I'm tending to think this isn't related to the plugin, but maybe you have any idea why this is happening and it might help you with the layout logic -

<img width="679" alt="screen shot 2015-09-28 at 6 56 42 pm" src="https://cloud.githubusercontent.com/assets/1858700/10140965/b5c4b818-6612-11e5-98ef-2dd11e870f6a.png">

Thanks!

**Comment by onevcat** [comment]
It goes well for me. Just to mention, the latest version in master branch is for Swift 2 and Xcode 7. If you are using Swift 1 and Xcode 6, you may need the [Xcode6 branch](https://github.com/onevcat/VVDocumenter-Xcode/tree/Xcode6) instead.

![snip20150929_1](https://cloud.githubusercontent.com/assets/1019875/10153031/2f5145c2-6693-11e5-84cd-16e993efea06.png)

**Comment by rolandleth** [comment]
I tried removing all plugins and it's still happening, so it's definitely unrelated.

Oh well, thanks for your time and sorry for bothering :)
