### ISSUE TITLE
Use spaces not working in Swift 2

### ISSUE THREAD

**Issue by diogoguimaraes** [onevcat/VVDocumenter-Xcode#182]
Use spaces instead of tabs setting is not producing any changes in the comment block.
I'm on Xcode7 using swift2.

![swiftbug](https://cloud.githubusercontent.com/assets/8330387/10194373/31db4f7a-6780-11e5-83df-9e405cb9a805.gif)

Any clue of what it may be?

**Comment by diogoguimaraes** [comment]
@onevcat any ideas on this issue? I'm on XcodeVersion 7.1.1 (7B1005).
Thank you.

**Comment by onevcat** [comment]
It is only used for align the parameters. If you try a method with multiple parameters, you may see the difference.
