### ISSUE TITLE
VVDocumenter crash?

### ISSUE THREAD

**Issue by iansul** [onevcat/VVDocumenter-Xcode#183]
Started getting this crash immediately after installing VVDocumenter on a new machine, but I've been using it with other machines for quite a while without any issue, so I'm not certain it's due to VVDocumenter...

    Thread 18 Crashed:: Dispatch queue: Clang QP lock
    0   libclang.dylib                	0x000000010e928c17 clang::comments::Lexer::lex(clang::comments::Token&) + 519
    1   libclang.dylib                	0x000000010e92c838 clang::comments::Parser::parseParagraphOrBlockCommand() + 14056
    2   libclang.dylib                	0x000000010e9f97b5 clang::RawComment::parse(clang::ASTContext const&, clang::Preprocessor const*, clang::Decl const*) const + 2629
    3   libclang.dylib                	0x000000010e8a8ff3 clang::ASTContext::getCommentForDecl(clang::Decl const*, clang::Preprocessor const*) const + 995
    4   libclang.dylib                	0x000000010df708d4 clang_Cursor_getParsedComment + 68
    5   com.apple.dt.IDEFoundation    	0x000000010c38cf2d __100-[IDEIndexClangQueryProvider parsedCodeCommentAtLocation:withCurrentFileContentDictionary:forIndex:]_block_invoke + 751
    6   libdispatch.dylib             	0x00007fff8d56cc13 _dispatch_client_callout + 8
    7   libdispatch.dylib             	0x00007fff8d56de5e _dispatch_barrier_sync_f_invoke + 57
    8   com.apple.dt.DVTFoundation    	0x000000010b86405d DVTDispatchBarrierSync + 62
    9   com.apple.dt.DVTFoundation    	0x000000010b606a37 -[DVTDispatchLock performLockedBlock:] + 116
    10  com.apple.dt.IDEFoundation    	0x000000010c25c088 -[IDEIndexClangQueryProvider performClang:] + 140
    11  com.apple.dt.IDEFoundation    	0x000000010c38ca85 -[IDEIndexClangQueryProvider parsedCodeCommentAtLocation:withCurrentFileContentDictionary:forIndex:] + 652
    12  com.apple.dt.IDEFoundation    	0x000000010c47e170 -[IDEIndex(IDEIndexQueries) parsedCodeCommentAtLocation:withCurrentFileContentDictionary:] + 109
    13  com.apple.dt.IDE.IDEQuickHelp 	0x000000011acedd40 __84-[IDEQuickHelpData queryCommentXMLFromIndexSymbol:expressionSource:completionBlock:]_block_invoke + 462
    14  com.apple.dt.DVTFoundation    	0x000000010b863ab0 __DVTDispatchAsync_block_invoke + 153
    15  libdispatch.dylib             	0x00007fff8d571323 _dispatch_call_block_and_release + 12
    16  libdispatch.dylib             	0x00007fff8d56cc13 _dispatch_client_callout + 8
    17  libdispatch.dylib             	0x00007fff8d570365 _dispatch_queue_drain + 1100
    18  libdispatch.dylib             	0x00007fff8d571ecc _dispatch_queue_invoke + 202
    19  libdispatch.dylib             	0x00007fff8d56f6b7 _dispatch_root_queue_drain + 463
    20  libdispatch.dylib             	0x00007fff8d57dfe4 _dispatch_worker_thread3 + 91
    21  libsystem_pthread.dylib       	0x00007fff911d6a9d _pthread_wqthread + 729
    22  libsystem_pthread.dylib       	0x00007fff911d43dd start_wqthread + 13

**Comment by onevcat** [comment]
It seems that Clang lever crashes on some comment. It should not be directly related to VVDocumenter, since the plugin did not use Clang and AST currently. However, there is a possibility that the produced comment causing it.

Does it crash when you open a specified file? It might contain some strange comment in it. If you could find which file and comment causes the problem, you may could file a radar to Apple.

**Comment by iansul** [comment]
Ok thanks.I haven't seen the crash after it happened twice in a row very quickly. I'll keep an eye out..

Sent from Outlook




On Fri, Oct 2, 2015 at 4:57 PM -0700, "Wei Wang" <notifications@github.com> wrote:
It seems that Clang lever crashes on some comment. It should not be directly related to VVDocumenter, since the plugin did not use Clang and AST currently. However, there is a possibility that the produced comment causing it.

Does it crash when you open a specified file? It might contain some strange comment in it. If you could find which file and comment causes the problem, you may could file a radar to Apple.

---
