### ISSUE TITLE
插件没有启动成功

### ISSUE THREAD

**Issue by LeoiOS** [onevcat/VVDocumenter-Xcode#188]
环境是 Xcode 7.1 正式版，在通过 Alcatraz 和 手动下载然后 Run 的方式下，重启 Xcode，插件都没有响应（输入 /// 没有变化），不知道原因是？

**Comment by theoxuan** [comment]
![image](https://cloud.githubusercontent.com/assets/5442563/10958821/208fdab2-83ad-11e5-8822-8237ddc4e7a0.png)
在<b>VVDocumenter-Xcode-Info.plist</b>里的<b> DVTPlugInCompatibilityUUIDs</b>下添加当前Xcode版本的UUID(xcode 7.1为<b>7265231C-39B4-402C-89E1-16167C4CC990</b>).
如果你不是此版本，可以自己手动查看: 进入Xcode.app打开它的<b>Info.plist</b>里面有UUID这一项
![image](https://cloud.githubusercontent.com/assets/5442563/10958884/b40f69ce-83ad-11e5-9cfd-34d72ab02187.png)<br/>
或者运行此命令`find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add &quote defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID &quote`
(注意此命令会修改所有现有插件的UUID列表; 将&quote替换为`,即 shift+~)

**Comment by LeoiOS** [comment]
@theoxuan 
谢谢！
尝试了一下该方法，发现我的 Xcode 版本就是 7.1，UUID 也是正确的。为了确认，去 Xcode.app 里面的 info.plist 中再次拷贝了 UUID 到 VVDocumenter 的 info.plist 中，然后运行，还是无效，输入 `///` 依然没有反应。
也尝试了 Alcatraz 安装，还是没反应哎。。。

**Comment by theoxuan** [comment]
你先删掉就的plugin，再重新Build，然后重启xcode
![vvdocumenter-xcode xcplugin](https://cloud.githubusercontent.com/assets/5442563/10959267/ae63d6c8-83b1-11e5-851d-0c5d176f7c0a.jpg)

不能传附件。。下载上面那张看不到的图改后缀为zip, 解压并拷贝到 
~/Library/Application Support/Developer/Shared/Xcode/Plug-ins

**Comment by theoxuan** [comment]
第一次启动Xcode会警告你 声称这个插件不是未认证。你选择Load Bundle就行了。这时候xcode会自动退出。再打开就好了。
如果没有出现这个提示，说明你已经禁用了此类插件。想办法改设置。

**Comment by LeoiOS** [comment]
@theoxuan 
非常感谢！可以了！
另外附件用图片传的方式也是机智！👍

**Comment by zfx5130** [comment]
@theoxuan  文件有什么不同吗, 我现在下载不了这个文件, 我也出现一样的问题,注释不成功

**Comment by theoxuan** [comment]
@zfx5130 
按照二楼的方法自己重新编译下～
记得确认自己的xcode版本（进入Xcode.app打开它的Info.plist里面有UUID）。

**Comment by zfx5130** [comment]
@LeoiOS 我的也遇到和你的一样的情况, 各种尝试安装, 都有不成功,最后你怎么解决的, 谢谢

**Comment by LeoiOS** [comment]
@zfx5130 
请看四楼和五楼！
