### ISSUE TITLE
Not working in Xcode 7+

### ISSUE THREAD

**Issue by fyxjsj** [onevcat/VVDocumenter-Xcode#191]
![dxj1kgt5tt](https://cloud.githubusercontent.com/assets/5609268/11108587/f15ec71e-8922-11e5-815b-a06bb4fffa8a.gif)

**Comment by onevcat** [comment]
Please check whether you are using some pasteboard managing apps (which might prevent other apps to put text into the pasteboard) or the the paste keyboard shortcut in Xcode is modified. VVDocumenter is using the system paste board to insert the documentation.

**Comment by nicolasiJasica** [comment]
I fixed it through 『defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1』.
 its me  don't select "Load bundles"  when install Xcode

**Comment by onevcat** [comment]
@fyxjsj Have made it work?

**Comment by driver733** [comment]
@onevcat Thanks! I had "Shift+Command+V" set as my default paste command. Revering it back to "Command+V" fixed the discussed issue.
