### ISSUE TITLE
Tuples as parameters

### ISSUE THREAD

**Issue by masa-beheim** [onevcat/VVDocumenter-Xcode#192]
Thanks for the plugin. I just noticed that return tuples work (https://github.com/onevcat/VVDocumenter-Xcode/issues/72) but parameter tuples still do not.
```swift
/**
 <#Description#>
 
 - parameter aTuple: <#aTuple description#>
 - parameter second: <#second description#>
 - parameter third:  <#third description#>
 
 - returns: <#return value description#>
 */
func testTuple(aTuple: (first: String, second: String, third: String)) -> (first: String, second: String, third: String)? {
    return nil
}
```

**Comment by alfredcc** [comment]
The same: missing the first element with tuple

**Comment by masa-beheim** [comment]
@alfredcc That is ok, it's not a parameter. The `second` and `third` are too much. It should look like:
```swift
/**
 <#Description#>

 - parameter aTuple: <#aTuple description#>

 - returns: <#return value description#>
 */
```

**Comment by dbettermann** [comment]
I found where the problem exists, but I would need to find some time to make a fix. Here's the line in case anyone wants to start.

https://github.com/onevcat/VVDocumenter-Xcode/blob/master/VVDocumenter-Xcode/Commenter/VVSwiftFunctionCommenter.m#L75

I copied the example function posted above into the VVMethodTestsCode.plist for debugging.

**Comment by onevcat** [comment]
@dbettermann Thanks! Let me do it. I just find some spare time now. :)

**Comment by onevcat** [comment]
Should be fixed in #194

**Comment by alfredcc** [comment]
Thanks！ 🎉🎉

**Comment by masa-beheim** [comment]
Great :sparkles:
