### ISSUE TITLE
not work in my Xcode7.1.1

### ISSUE THREAD

**Issue by zfx5130** [onevcat/VVDocumenter-Xcode#195]
I use  Alcatraz install , but not succeed,  and i  immediate download ,and install ,but not succeed, and i see the UUID is the same , why my xcode is not succeed

**Comment by DaRkD0G** [comment]
+1

**Comment by panderman** [comment]
xcode7.2 work fine

**Comment by DaRkD0G** [comment]
No for Swift

**Comment by igiu1988** [comment]
Delete old plugin, reinstall, restart Xcode，then Xcode will show a dialog asking you load plugin bundle or not, be sure click "load".

**Comment by onevcat** [comment]
I am closing this since you can find more information in [Xcode Version](https://github.com/onevcat/VVDocumenter-Xcode#xcode-version) of README. Try to reset the "Load Bundle" option if you happened to forbid third party bundle.
