### ISSUE TITLE
添加description时主动换行？

### ISSUE THREAD

**Issue by luna-moonfang** [onevcat/VVDocumenter-Xcode#200]
不知道是否已有这个功能但我没发现。

有时对一个属性或方法的说明比较多，想分成多行，看起来更清晰。现在是无论在 `/**` 后面怎么换行，description都会连起来，到达最大宽度时再折行。

**Comment by onevcat** [comment]
属性似乎没什么办法..或者我不知道..可能 Xcode 在做 parsing 的时候确实是就不可以吧...

P.S. 我也很喜欢月骑。
