### ISSUE TITLE
喵神, 这个插件支持Xcode7.2吗

### ISSUE THREAD

**Issue by WangGuibin** [onevcat/VVDocumenter-Xcode#203]
喵神, 这个插件支持Xcode7.2吗,前几天刚升级的7.2,发现这个插件呼不出来了...

**Comment by liuxuan30** [comment]
支持.

**Comment by YK-Unit** [comment]
XCode7.2。 在 Alcatraz 上remove，reinstall，还是无法使用。

**Comment by lujinxin** [comment]
7.2可以用，一直在用。

Stay hungry  , stay foolish .

**Comment by liuxuan30** [comment]
此贴可以close

**Comment by onevcat** [comment]
@WangGuibin 支持的。如果有问题的话可以尝试 Clean 重新 Build 一下，或者看一下 README 里的 [Xcode Version](https://github.com/onevcat/VVDocumenter-Xcode#xcode-version) 部分重置一下 Load Bundle
