### ISSUE TITLE
注释可以记录当前时间么?

### ISSUE THREAD

**Issue by chengxxxxwang** [onevcat/VVDocumenter-Xcode#220]
我使用VVDocumenter注释的时候有时候想要记下时间方便以后查看,我想问一下VVDocumenter可以实现么怎么使用,可以手动打开关闭时间记录么?

**Comment by igiu1988** [comment]
Xcode-windows-VVDocumenter的设置里有。好像Swift里并不生效，所以你可以自己改改源码

**Comment by chengxxxxwang** [comment]
好的,我去试试
