### ISSUE TITLE
Xcode plugin has bugs when I used,how I can update it conveniently when I know author fix it？

### ISSUE THREAD

**Issue by zdrjson** [onevcat/VVDocumenter-Xcode#223]

**Comment by onevcat** [comment]
You could use [Alcatraz](http://alcatraz.io) to reinstall it, or clone the repo and build it again in your Xcode.

**Comment by zdrjson** [comment]
安装了多个插件,插件更新了,只能一个一个重新安装吗？

**Comment by igiu1988** [comment]
# Add new UUID of Xcode to plugins
alias xcplug="find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`"
