### ISSUE TITLE
Support property/method grouping per @name

### ISSUE THREAD

**Issue by dploeger** [onevcat/VVDocumenter-Xcode#62]
I'm not quite sure, if this can be automatically detected by VVDocumenter, but it would be great to create property/method-groups using the @name-property like described in http://nshipster.com/documentation/.

If no automation is possible, perhaps a secondary tag could be used (//* for example), to automatically insert the documentation stub.

**Comment by onevcat** [comment]
It seems this is rarely used. And currently it does not an easy pie VVDocumenter to automatically detect the related property/method group. So I guess it will not added.

The using of `#pragma mark` is a more popular way, and you might be already using a snippet for it.
