### ISSUE TITLE
Support extension comments

### ISSUE THREAD

**Issue by grosch** [onevcat/VVDocumenter-Xcode#82]
Per the very popular Ray Wenderlich style guide, extensions should be commented like so:

```Swift
// MARK: - UITableViewDelegate
extension SomeViewController: UITableViewDelegate {
}
```

Can you modify the /// expansion so that if it's looking at an extension that includes a delegate then it puts the MARK there with the single leading - character?

**Comment by onevcat** [comment]
Good idea. Add it later.

**Comment by onevcat** [comment]
Should be added in #122
