### ISSUE TITLE
Support var arguments in Swift functions

### ISSUE THREAD

**Issue by jpsim** [onevcat/VVDocumenter-Xcode#83]
Swift supports making a mutable copy of an argument by prefixing its name with `var`.

However, VVDocumenter fails to parse the function signature when using this feature.

```swift
/**
<#Description#>

:param: a <#a description#>
*/
func testA<A>(a: A) {}

/// <#Description#>
func testB<B>(var b: B) {}
```

**Comment by onevcat** [comment]
Supported by @Garnel 's p-r. Thanks!
