### ISSUE TITLE
Can't build with 10.10 Base SDK (10.9 is OK) in Xcode 6.1

### ISSUE THREAD

**Issue by binderclip** [onevcat/VVDocumenter-Xcode#85]
![qq20150128-1](https://cloud.githubusercontent.com/assets/8187479/5930820/fdb0f6a8-a6cf-11e4-87ac-7927e7bdf198.png)

Change the `Base SDK` to 10.9 can successful build and install the plugin. :smile: 

Don't know if this can say a bug. :bug:

**Comment by onevcat** [comment]
I will check it later. :(

**Comment by onevcat** [comment]
No idea since I can not reproduce this issue. I am closing it. If this problem persists, I will consider to file a radar.
