### ISSUE TITLE
Swift - Missing *

### ISSUE THREAD

**Issue by NicolaiSchnack** [onevcat/VVDocumenter-Xcode#87]
/**
    <#Description#>
    
    :param: message  <#message description#>
    :param: autohide <#autohide description#>
    */
    func showStatus(message : String, autohide : Double = 0.0){

**Comment by onevcat** [comment]
* will not be recognized by Xcode inline documentation parser, so the * setting is ignored in Swift source.

**Comment by NicolaiSchnack** [comment]
Oh, thx!
