### ISSUE TITLE
C++ parameters like std::string are incomplete 

### ISSUE THREAD

**Issue by vladubogdan** [onevcat/VVDocumenter-Xcode#89]
This is what is produced for a method like the following.

/**
     <#Description#>
     
     :param: std <#std description#>
     
     :returns: <#return value description#>
     */
    virtual bool initWithContentOfFile(const std::string& plistLevelFile);

**Comment by onevcat** [comment]
Hi, this plugin does not support for C++ code currently. I will consider to add C++ support later, but now only Objective-C and Swift code is considered.
