### ISSUE TITLE
Code completion in xCode

### ISSUE THREAD

**Issue by zaachi** [onevcat/VVDocumenter-Xcode#90]
xCode version 6.1.1

Without VVDocumenter 
![snimek obrazovky 2015-02-17 v 15 40 50](https://cloud.githubusercontent.com/assets/458030/6229963/1889d714-b6bc-11e4-94b4-ee417de207f1.png)

with VVDocumenter-Xcode
![snimek obrazovky 2015-02-17 v 15 41 58](https://cloud.githubusercontent.com/assets/458030/6229967/207736f6-b6bc-11e4-820c-d648ff186cfa.png)

**Comment by onevcat** [comment]
Hi, VVDocumenter will do nothing about auto completion or popup. It might be due to some other plugins. Would you please to check if you have other plugins installed or try to use VVDocumenter in a clean Xcode?

**Comment by zaachi** [comment]
No other plugin has not installed.

**Comment by onevcat** [comment]
@zaachi  Quite strange. Any update on this issue? Or is there anything useful in Console?

**Comment by onevcat** [comment]
:( Anyway, I am closing it.
