### ISSUE TITLE
Detect keyboard shortcuts

### ISSUE THREAD

**Issue by ZevEisenberg** [onevcat/VVDocumenter-Xcode#92]
The readme states:

> The plugin is using simulation of keyboard event to insert the doc comments for you. So it is depending the keyboard shortcut of Xcode. These two kinds of operation are being used:
> 
> - Delete to Beginning of the Line (⌘⌫)
> - Paste (⌘V)

You should be able to read the keyboard shortcuts out of `~/Library/Developer/Xcode/UserData/KeyBindings`.

And you could read the default Mac keyboard shortcuts out of `~/Library/Preferences/.GlobalPreferences.plist`.

For more on how keyboard shortcuts are stored in preference files, you may find [this blog post](http://www.raizlabs.com/dev/2015/02/how-to-script-os-x-keyboard-shortcuts/) that I wrote helpful.

This isn't an issue that affects me, so I don't know if it's a priority, but it occurred to me that this would be a way to avoid the limitation of requiring standard keyboard shortcuts for those commands.

**Comment by onevcat** [comment]
It could be a great improvement! 

Thanks for pointing it out. I will read it and update soon.

**Comment by onevcat** [comment]
It seems if users are using a customized set of keybindings, a new file with `{set-name}.idekeybindings` will be generated in the `~/Library/Developer/Xcode/UserData/KeyBindings`. That means we should know which set is currently used. I guess there would be a way to get it from Xcode private framework. I will check it later when I have time.

**Comment by onevcat** [comment]
It turns out too hack to do it, and currently VVDocumenter does not importing any private framework. If we want to add this feature, we have to rely on private framework, which is a high risk action. So I decide not to add it.
