### ISSUE TITLE
Time shows not correct.

### ISSUE THREAD

**Issue by iYiming** [onevcat/VVDocumenter-Xcode#94]
When I selected  "Add Date" ,Time shows not correct. Hour is correct ,but minute is always 2 . Now is 7:49 pm , please see my attach image.  Thanks!

![5264ff54-8139-4f1b-a703-73a6e5c0f986](https://cloud.githubusercontent.com/assets/3022390/6412049/d8775c54-beb9-11e4-90c2-6ccf87e070c4.png)

![ce6b33b2-c8cb-458a-876d-9ef51f0e34dc](https://cloud.githubusercontent.com/assets/3022390/6412027/a19171e8-beb9-11e4-865c-f2ada284c58d.png)

**Comment by chenshengzhi** [comment]
the format should be : yy-MM-dd HH:mm:ss
