### ISSUE TITLE
Synchronization between .h and .m file

### ISSUE THREAD

**Issue by Matthijn** [onevcat/VVDocumenter-Xcode#95]
First off, lovely plugin. It really makes creating appledoc much easier.

However it would be nice that if you add or change an appledoc comment to a method / property etc in the .h file it will automatically add and update that appledoc comment to the .m file. 

Now I am copying and pasting a bunch of those comments around. Don't know if this idea is feasible though.

**Comment by onevcat** [comment]
Hi, @Matthijn 
Thanks for your kind word and the advice.

However, this could be quite complicated based on current code. VVDocumenter is started as a project to help writing public (header) docs and just handling current file only. Moreover, the internal (implementation) docs is not so widely needed and the synchronization between them could also be a concern.

I guess this will not be implemented in the project. Another new utility which could sync comment docs between header and source would be a better idea.
