### ISSUE TITLE
Xcode6.1.1 menu Window-->VVDocumenter doesn't do anything

### ISSUE THREAD

**Issue by benhj** [onevcat/VVDocumenter-Xcode#96]
Firstly thanks for the great plugin:-
I would like to change the trigger from '///' to something else, but selecting Window-->VVDocumenter doesn't do anything. No window is displayed. Nothing. 

Many thanks.
Ben.

**Comment by onevcat** [comment]
Hi, 
Would you please try to build it from source instead of using Alcatraz, in which there is a bug preventing xib files built.

You may see this issue for more information https://github.com/supermarin/Alcatraz/issues/196

**Comment by benhj** [comment]
Many thanks but I did build from source.

**Comment by onevcat** [comment]
It must be some thing wrong that the plugin can not find/open the xib file.

So would you please try to give it a clean and rebuild? Open VVDocumenter project, and use Shift+Cmd+K then do a Shift+Cmd+Option+K.

I just tested in my Xcode 6.1.1 and it works fine for me.

**Comment by onevcat** [comment]
If the error persists, would you please paste some log about it? I believe you can find something useful in the Console.app.

Thanks and best regards.

**Comment by benhj** [comment]
Many thanks! I think I must have done something weird when I originally tried this. With Xcode closed, I recursively removed the plugin then went through your above suggested steps finishing with Cmd+B, then restarting Xcode and the window now appears :-)

Cheers!
