### ISSUE TITLE
Doesn't work on Xcode 6.2

### ISSUE THREAD

**Issue by soloxiao** [onevcat/VVDocumenter-Xcode#98]
I updated to Xcode 6.2 today, it doesn't work any more even I build it again. I can find the plug-in in the directory.

**Comment by johanwigmo** [comment]
Try adding `A16FF353-8441-459E-A50C-B071F53F51B7` to the `DVTPlugInCompatibilityUUIDs`array in the Info.plist

**Comment by davidolesch** [comment]
Thank you @johanwigmo. That fixes it for me.

**Comment by onevcat** [comment]
It's added in https://github.com/onevcat/VVDocumenter-Xcode/commit/8bce8989a67015d1b384b15806e024ffd090b3cc . You need to update and build it again.
