### ISSUE TITLE
Doesn't appear to be working in Xcode 6.2

### ISSUE THREAD

**Issue by khendry** [onevcat/VVDocumenter-Xcode#99]
I have this plugin installed with Alcatraz and the "///" does nothing.

**Comment by brennon** [comment]
+1

**Comment by dujiazzj** [comment]
+1

**Comment by brennon** [comment]
Removing the plugin through Alcatraz, cloning the project, and building the project fixed the problem for me.

**Comment by dujiazzj** [comment]
can't build success in Xcode 6.2

**Comment by brennon** [comment]
What error are you getting?

**Comment by dujiazzj** [comment]
ld: warning: ObjC object file (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/CoreService.framework/CoreService) was compiled for iOS Simulator, but linking for MacOSX
ld: framework not found CoreImage for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dujiazzj** [comment]
I remove the file in DerivedData that solve the problem

**Comment by SLboat** [comment]
@dujiazzj 看起来平台选择的有问题,清理编译,再次编译,重新下载?我这里一次就成..

**Comment by AJ9** [comment]
+1

**Comment by LengBinBin** [comment]
remove the plug in path : ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins 
    named:VVDocumenter-Xcode.xcplugin,
then Relaunch Xcode , /// works well in Xcode6.2  : )

**Comment by Opencil** [comment]
@dujiazzj i got the same problem with you, can you share your solution?

**Comment by alemar11** [comment]
it works without Alcatraz

**Comment by khendry** [comment]
@alemar11 Thanks.  Good to know.

**Comment by gmaletic** [comment]
+1

**Comment by onevcat** [comment]
It seems not a problem within VVDocumenter. I tested it with the new version of Alcatraz and everything goes well for me.

If you can not get it work, just try @LengBinBin 's advice to recompile it from the latest master. Or just use Alcatraz 1.1 to install.

@dujiazzj It seems you are specifying an iOS platform instead of OSX. You should build the `VVDocumenter-Xcode` target in the project.

I am closing it.

**Comment by gmaletic** [comment]
This should not be closed. It does not work, even when using Alcatraz 1.1.

**Comment by Opencil** [comment]
I had to back to 6.1.1 to using vvdoc.

**Comment by onevcat** [comment]
@gmaletic What about build from source manually? Clone the master and then build in Xcode 6.2

**Comment by dujiazzj** [comment]
@onevcat It is Xcode 6.2 bug.I can't build any mac application.

**Comment by onevcat** [comment]
@dujiazzj Thanks for your feedback.

**Comment by paulmix** [comment]
I had the same issue: the plug-in (installed either through Alcatraz or built from commit 4b56c62) wasn't showing up in Xcode 6.2. I tried removing the plug-in manually and via Alcatraz with no luck.

I was finally able to get Xcode 6.2 to see it by:
1. Removing the plug-in manually
2. Opening VVDocumenter.xcodeproj in Xcode 6.2
3. Clean-all VVDocumenter.xcodeproj
4. Quit Xcode 6.2
5. Manually delete DerivedData folder for VVDocumenter.xcodeproj
6. Re-open VVDocumenter.xcodeproj in Xcode 6.2
7. Build VVDocumenter
8. Quit and re-launch Xcode 6.2

**Comment by idStar** [comment]
@paulmix I tried your approach (something similar to this worked for me in the past). Sadly, those steps didn't work for me this time.

**Comment by paulmix** [comment]
I'll see how long it lasts; Xcode seems to frequently lose track of the plug-in for some reason, forcing me to uninstall/reinstall. Wish I had cycles to investigate the root cause of this further, as it's a pain frequently reinstalling it.

**Comment by onevcat** [comment]
This issue never happens on my Mac, so I can not tell what happened at all.
Maybe an Xcode bug? I will keep an eye on it and wait for more information.

**Comment by xx314327475** [comment]
@LengBinBin  work for me!Thank you.

**Comment by paulmix** [comment]
It's re-appeared and disappeared at least once more in Xcode 6.2 since I installed it. Seems to come and go with no (as-of-yet) perceivable pattern.

**Comment by paulmix** [comment]
There is still something odd going on. The copy installed on 4/9 on my 2009 MacPro has continued to load with no issues, but I just tried installing from the same sources on a copy of Xcode 6.3 installed on my 2011 MBP, and that install of Xcode 6.3 refused to show the plug-in in the menu. Both machines are running 10.10.3, with Xcode 6.3 installed in /Applications from the same dmg. I manually copied the installed copy of the plug-in from my MacPro to my MBP, and it still doesn't show up. I finally had to follow my steps from a month ago to get it to show up; however, based on past experience, I'm not confident it'll remain.

**Comment by liuxuan30** [comment]
I use VVDoc from 6.1 to 6.3 and works perfect. I don't use Alcatraz

**Comment by dujiazzj** [comment]
@liuxuan30  me too

**Comment by khendry** [comment]
Seems to be working now in 6.3 using Alcatraz. At least for me.

**Comment by jacobvanorder** [comment]
FWIW, I got it to work by removing the plugin, deleting derived data and reinstalling. YMMV.

**Comment by idStar** [comment]
@jacobvanorder That's been working for me too. Clearing derived data and re-installing, usually works within 1-2 attempts of going through that cycle.

**Comment by onevcat** [comment]
It seems no new report for Xcode 6.3. So I guess it might be a bug in Xcode 6.2 which prevents plugin loading in some case.

I am closing this issue.

**Comment by khendry** [comment]
Yeah, I've had it working in 6.3. It did start working in 6.2 if I installed manually. So I think it was probably an issue either with Alcatraz or with my installation of Alcatraz at the time.  I appreciate you looking into it though.
